version: '3'

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:

  jupyterlab:
    build:
      context: ./devops/jupyterlab
      dockerfile: Dockerfile
    image: "dockerhub.aganitha.ai:4443/dev/unidock-image-kailash"
    container_name: ${USER}-unidock-jupyter
    ports:
      - "4000:4000"
    environment:
      - PG_HOST=postgres
      - PG_PORT=5000  
      - PG_USER=jupyter_user
      - PG_PASSWORD=jupyter_password
      - PG_DB=jupyter_db
    depends_on:
      - postgres
    runtime: nvidia
    volumes:
      - ./main:/home
    labels:
      - "description=Jupyterlab_for_UniDock"
      - "port=4000"
    networks:
      - my_network

  postgres:
    build:
      context: ./devops/pg
      dockerfile: Dockerfile
    image: unidock-postgres-kailash
    container_name: ${USER}-unidock-postgres
    environment:
      - POSTGRES_USER=demo_user
      - POSTGRES_PASSWORD=demo_password
      - POSTGRES_DB=demo_db
    volumes:
      - ./devops/pg/database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./devops/pg/ligands_smiles.csv.gz:/ligands_smiles.csv.gz
    labels:
      - "description=PostgreSQL_for_UniDock"
      - "port=5000"
    networks:
      - my_network
